version: '3'

services:
  vpn:
    build: .
    container_name: ikev2-server
    privileged: true
    volumes:
      - './data/certs/certs:/etc/ipsec.d/certs'
      - './data/certs/private:/etc/ipsec.d/private'
      - './data/certs/cacerts:/etc/ipsec.d/cacerts'
      - './data/etc/ipsec.d/ipsec.secrets:/etc/ipsec.secrets'
    environment:
      - VPNHOST=
      - LEEMAIL=
    ports:
      - '500:500/udp'
      - '4500:4500/udp'
      - '80:80'
  