version: '3'

services:
  vpn:
    build: .
    container_name: ikev2-vpn-server
    privileged: true
    volumes:
      - './data/etc/ipsec.d/ipsec.secrets:/usr/local/etc/ipsec.secrets'
      - './data/etc/letsencrypt:/etc/letsencrypt'
    env_file:
      - .env
    ports:
      - '500:500/udp'
      - '4500:4500/udp'
    networks:
      - backend
networks:
  backend:
    ipam:
      config:
        - subnet: 10.0.0.0/24